#!/bin/bash
IFS=$'\n'

# $THEME env variable set via sway config.

# check for env variable, if exists we are the
# forked shell, get the waiting string from the fifo
# and call fzf and sway from there.
prompt="Windows> "
if [[ -n $fifo ]]; then
    str=$(cat $fifo)
    rm -rf $fifo

    selection=$(printf $str | fzf --prompt="$prompt" --color=$THEME)

    id=$(echo $selection | cut -d ":" -f1)
    if [[ -z $id ]]; then
        exit
    fi

    swaymsg [con_id="$id"] focus
    notify-send -u low "moved to window $selection"
    exit
fi


fifo=/tmp/som-$(date +%s)
mkfifo $fifo
fifo=$fifo zsh -c "alacritty \
    -o window.dimensions.columns=$columns \
    -o window.dimensions.lines=$lines \
    -o font.size=16.0 \
    -o window.padding.x=20 \
    -o window.padding.y=20 \
    --title "fzf-switcher" \
    -e /home/louis/git/dotfiles/config/sway/scripts/som"&
echo -n $str > $fifo
