lastupdatecheck: 0
recentrepos:
- /home/louis/git/gopath/src/github.com/cilium/cilium-enterprise
- /home/louis/git/dotfiles
startuppopupversion: 5
customcommandshistory:
- qa!
hidecommandlog: false
ignorewhitespaceindiffview: false
