lastupdatecheck: 0
recentrepos:
    - /home/louis/git/c/linux-bpf-next
    - /home/louis/git/c/ebpf-playground
    - /home/louis/git/gopath/src/github.com/cilium/cilium-enterprise
    - /home/louis/git/dotfiles
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.54.1
customcommandshistory:
    - qa!
hidecommandlog: true
