# K9s Gruvbox Light Skin Contributed by [@indiebrain](https://github.com/indiebrain)
foreground: &foreground "#1D344F"
background: &background "#FFFFFF"
current_line: &current_line "#6080b0"
selection: &selection "#6080b0"
comment: &comment "#767B85"
cyan: &cyan "#40626B"
green: &green "#5A7C6B"
orange: &orange "#BA774A"
magenta: &magenta "#4c4c4c"
blue: &blue "#5070a0"
red: &red "#B95D76"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *blue
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *orange
  info:
    fgColor: *magenta
    sectionColor: *foreground
  help:
    fgColor: *foreground
    bgColor: *background
    keyColor: *magenta
    numKeyColor: *blue
    sectionColor: *green
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *magenta
    buttonFocusFgColor: white
    buttonFocusBgColor: *cyan
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *magenta
      numKeyColor: *magenta
    crumbs:
      fgColor: *foreground
      bgColor: *comment
      activeColor: *blue
    status:
      newColor: *cyan
      modifyColor: *blue
      addColor: *green
      errorColor: *red
      highlightcolor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *background
      highlightColor: *orange
      counterColor: *blue
      filterColor: *magenta
  views:
    charts:
      bgColor: background
      defaultDialColors:
        - *blue
        - *red
      defaultChartColors:
        - *blue
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      cursorFgColor: *foreground
      cursorBgColor: *current_line
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *selection
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *blue
      showIcons: false
    yaml:
      keyColor: *magenta
      colonColor: *blue
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *background
